server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false
    username: root
    password: 8818165957
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

indexing-settings:
  sites:
    - url: https://volochek.life/
      name: volochek
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru

indexing:
  user-agent: "Mozilla/5.0 (compatible; HeliontSearchBot/1.0; +http://mysearchbot.com)"
  delays:
    default: 200
    site-specific:
      "skillbox.ru": 150
  max-pages-per-site: 20000
  timeout-ms: 30000
  min-delay-ms: 100
  max-retries: 3
  max-depth: 5
  max-concurrent-pages: 18
  site-depths:
    "skillbox.ru": 5
    "volochek.life": 3
  exclude-patterns:
    - .*\.(webp|jpg|jpeg|png|gif|pdf|zip|rar|docx|xlsx|pptx|mp3|mp4|avi)$
    - /api/
    - /admin/
    - /payment/

logging:
  level:
    root: INFO
    searchengine: INFO
    org.hibernate.SQL: WARN